#! /usr/bin/perl
#
use strict;
use warnings;

use YAML::XS qw/LoadFile/;
use Data::Dumper;

my $pipeline_config = shift @ARGV;
my $bricks_directory = 'bricks/';

my $config  = LoadFile($pipeline_config);

print "## THIS FILE HAS BEEN GENERATED BY 'makePipe v0.0' from $pipeline_config\n";

# Variables definition
my @all = ();
my @clean = ();
my $vars = "##############################\n#          VARIABLES         #\n##############################\n\n";
my $rules = "##############################\n#            RULES           #\n##############################\n\n";

# Include "CORE" brick
#unshift(@all,"core");
$config->{core}->{brick} = "CORE";

foreach my $process (keys %{$config}) {
  my $brick = $config->{$process}->{brick};
  my $brick_file = "$bricks_directory/$brick.Makefile";

  if(!-e $brick_file) {
    print STDERR "brick $brick not found in bricks directory: $bricks_directory\n";
    next;
  }

  open (my $fh,$brick_file) or die ("Cannot open $brick_file");
  $vars .= "# Process: $process, constructed from BRICK $brick\n";
  $rules .= "# Process: $process, constructed from BRICK $brick\n";
  while(<$fh>) {
    # Skip comments
    next if $_ =~ /^#/;
    # Skip blank lines
    next if $_ =~ /^\s*$/;
    #my($var,$value) = $_ =~ /^%%_(\S+)\s*=\s*(.*)$/;
    my($var,$value) = $_ =~ /^%%_(\S+)\s*=\s*(.*)$/;
    # If this line correspond to a variable assignement
    # we check if a new value is defined in the pipeline config
    if(defined $var && defined $value) {
      my $new_val = $config->{$process}->{config}->{$var};
      if(defined $new_val) {
        $value = $new_val;
      }
      $value =~ s/%%/$process/g;
      die ("Undef value for variable $var in process $process") if $value eq 'undef';
      $vars .= $process."_"."$var = $value\n";
    } else {
      # We add the process to the all: target if a PHONY rule exists for this
      # process
      push @all, $process if($_ =~ /^%%:/);
      # Same for clean rule
      push @clean, $process if($_ =~ /^%%_clean:/);
      $_ =~ s/%%/$process/g;
      $rules .= $_;
    } 
  }
  #print "\n";
  $vars .= "\n";
  $rules .= "\n";
}

# Print "all:" rule
print "\nall: ".join(" ", @all)."\n.PHONY: all\n\n";

# Print vars
print $vars;

# Print rules
print $rules;

# print clean target
print "clean: ".join(" ",map { $_."_clean" } @clean),"\n";


# TODO add rm

#print Dumper($config);
