## THIS FILE HAS BEEN GENERATED BY 'makePipe v0.0' from pipeline.yml

all: $(lastword $(MAKEFILE_LIST))
.PHONY: all

$(lastword $(MAKEFILE_LIST)): pipeline.yml
	./makepipe build $< > $@

##############################
#          VARIABLES         #
##############################

##############################
#            RULES           #
##############################

clean: 
