---
config:
  nb_threads: 4
  nb_jobs: 2
  genome_name: GRCh38
  counts: "quantification/gene_counts.tsv"
samples:
  - name: test1 
    type: TOTO
  - name: test2 
    type: TATA
#core:
#  brick: CORE
#  config:
#    INDEX_DIRECTORY: /data/indexes
crac:
  brick: CRAC
  #execution: serial
  config:
    INDEX: "/data/indexes/crac/{{config.genome_name}}"
    BINARY: /data/projects/crac-dev/src/crac
    OPTIONS: --no-ambiguity
    KMER_LENGTH: 22
    READS: "raw/{{item.name}}_1.fastq raw/{{item.name}}_2.fastq"
    OUTPUT_PREFIX: "mapping/crac/{{item.name}}"
    NB_THREADS: "{{config.nb_threads}}"
    #READS: 
    #  - "raw/{{item.name}}_1.fastq"
    #  - "raw/{{item.name}}_2.fastq"
    #OUTPUT: "mapping/crac-{{crac.version}}/{{item.name}}.bam"
  loop: 
    list: samples
    id: name
  export: 
    - value: "{{this.OUTPUT_FILE}}"
      to: item.sam_file

cractools:
  brick: CRACTOOLS_EXTRACT
  config:
    SAM_FILE: "{{item.sam_file}}"
    CHIMERA_OUTPUT_PREFIX: "chimeras/cractools/{{item.name}}"
    SPLICE_OUTPUT_PREFIX: "splices/cractools/{{item.name}}"
    MUTATION_OUTPUT_PREFIX: "mutations/cractools/{{item.name}}"
    NB_THREADS: "{{config.nb_threads}}"
  loop: 
    list: samples
    id: name
    export: 
      - value: "{{this.CHIMERA_OUTPUT}}"
        to: tem.chimeras 
      - value: "{{this.SPLICE_OUTPUT}}"
        to: item.splices
      - value: "{{this.MUTATION_OUTPUT}}"
        to: item.mutations

counts:
  brick: FEATURECOUNTS
  config:
    ANNOTATION_FILE: /data/annotations/human/Homo_sapiens.GRCh38.77.gtf
    INPUT_ALIGNMENTS: "{{samples.extract('sam_file')}}"
    OUTPUT_FILE: "{{config.counts}}"
  


chimCT:
  brick: CHIMCT
  config:
    SAM_FILE: "{{item.sam_file}}"
    ANNOTATION_FILE: /data/annotations/human/ensembl.gff
    OUTPUT_FILE: "chimeras/chimCT/{{item.name}}-chimeras.csv"
  loop:
    list: samples
    id: name
    export: 
      - value: "{{this.OUTPUT_FILE}}"
        to: item.chimct_file

# CREATE a gziped file from the gene counts
test:
  brick: GENERIC
  config:
    INPUT_FILE: "{{config.counts}}"
    OUTPUT_FILE: "{{config.counts}}.gz"
    COMMAND_LINE: "gzip {{config.counts}} -c > {{config.counts}}.gz"

# Print the first lines of the gene counts file
test2:
  brick: GENERIC
  config:
    INPUT_FILE: "{{config.counts}}"
    COMMAND_LINE: "head {{config.counts}}"
