## DESCRIPTION
# CRAC is a Mapping softwares that is able to align spliced reads to a reference genome.

## INPUT VARS:
%%_INDEX 							= undef # Filename of the index to be used
%%_READS 							= undef # List of reads files (FASTA or FASTQ) to be passed to CRAC

## OUTPUT VARS
%%_OUTPUT_FILE				= undef # SAM/BAM file generated by CRAC

## OPTIONS
%%_BINARY 						= crac # Binary to use for running CRAC
%%_KMER_LENGTH 				= 22 # Size of the k-mer used by CRAC
%%_OPTIONS 						= # Options that can be specified to CRAC (run `crac -f` for more information) 

## COMPUTED VARS
%%_VERSION 						= $(shell $(%%_BINARY) -v | head -1 | cut -d " " -f 3)
%%_OPTIONS += -i $(%%_INDEX) -k $(%%_KMER_LENGTH) --bam
%%_OUTPUT_EXTENSION 	= $(suffix $(%%_OUTPUT_FILE))

#%%_RAWS = undef
#%%_READS_DIRECTORY 		= raw
#%%_READS_EXTENSION 		= .fastq
#%%_FIRST_PAIR_SUFFIX 	= _1
#%%_SECOND_PAIR_SUFFIX	= _2
#%%_OUTPUT_DIRECTORY 	=	$(core_MAPPING_DIRECTORY)/%%-$(%%_VERSION)
#%%_OUTPUT_EXTENSION 	= .bam
#%%_REMOVE_SAMS 				= false

#OUTPUT VARS
#%%_RAWS_FILENAMES = $(notdir $(%%_RAWS))
#%%_SAMS 							= $(addprefix $(%%_OUTPUT_DIRECTORY)/, $(addsuffix $(%%_OUTPUT_EXTENSION), $(%%_SAMPLES)))

#COMPUTED VARS

.PHONY: %%
%%: $(%%_OUTPUT_FILE)

%%_clean:
	-rm $(%%_OUTPUT_FILE)
	#-rm -rf $(%%_OUTPUT_DIRECTORY)

.SERIAL: $(%%_OUTPUT_FILE)
$(%%_OUTPUT_FILE): $(%%_READS)
	mkdir -p $(dir $@)
	$(%%_BINARY) $(%%_OPTIONS) -r $(wordlist 1, 2, $^) -o - --summary $(@:$(%%_OUTPUT_EXTENSION)=-summary.txt) 2> $(@:$(%%_OUTPUT_EXTENSION)=.log) | samtools sort - $(@:%$(%%_OUTPUT_EXTENSION)=%)
	samtools index $@
