#%%_INPUT_ALIGNMENTS						= undef
%%_SAMPLES										= undef
%%_ALIGNMENTS_DIRECTORY				= undef
%%_ALIGNMENTS_EXTENSION				= .bam
%%_SPLICES_OUTPUT_DIRECTORY 	= $(core_SPLICES_DIRECTORY)/%%
%%_MUTATIONS_OUTPUT_DIRECTORY = $(core_MUTATIONS_DIRECTORY)/%%
%%_CHIMERAS_OUTPUT_DIRECTORY 	= $(core_CHIMERAS_DIRECTORY)/%%
%%_SPLICES_EXTENSION 					= -splices.bed
%%_MUTATIONS_EXTENSION				= .vcf
%%_CHIMERAS_EXTENSION					= -chimeras.tsv
%%_BINARY											= cractools-extract
%%_OPTIONS										= --coverless-splices


%%_OUTPUT_CHIMERAS = $(addprefix $(%%_CHIMERAS_OUTPUT_DIRECTORY)/, $(addsuffix $(%%_CHIMERAS_EXTENSION), $(%%_SAMPLES)))
%%_OUTPUT_SPLICES = $(addprefix $(%%_SPLICES_OUTPUT_DIRECTORY)/, $(addsuffix $(%%_SPLICES_EXTENSION), $(%%_SAMPLES)))
%%_OUTPUT_MUTATIONS = $(addprefix $(%%_MUTATIONS_OUTPUT_DIRECTORY)/, $(addsuffix $(%%_MUTATIONS_EXTENSION), $(%%_SAMPLES)))

%%: $(%%_OUTPUT_SPLICES)

$(%%_SPLICES_OUTPUT_DIRECTORY) $(%%_MUTATIONS_OUTPUT_DIRECTORY) $(%%_CHIMERAS_OUTPUT_DIRECTORY):
	mkdir -p $@

#$(%%_OUTPUT_CHIMERAS) $(%%_OUTPUT_MUTATIONS)

#$(%%_OUTPUT_CHIMERAS): $(%%_OUTPUT_SPLICES)
#
#$(%%_OUTPUT_MUTATIONS): $(%%_OUTPUT_SPLICES)

#$(%%_OUTPUT_SPLICES): $(%%_INPUT_ALIGNMENTS)

$(%%_SPLICES_OUTPUT_DIRECTORY)/%$(%%_SPLICES_EXTENSION): $(%%_ALIGNMENTS_DIRECTORY)/%$(%%_ALIGNMENTS_EXTENSION) 
	@mkdir -p $(%%_SPLICES_OUTPUT_DIRECTORY) $(%%_MUTATIONS_OUTPUT_DIRECTORY) $(%%_CHIMERAS_OUTPUT_DIRECTORY)
	$(%%_BINARY) $(%%_OPTIONS) $< -s $@ -m $(*:%=$(%%_MUTATIONS_OUTPUT_DIRECTORY)/%$(%%_MUTATIONS_EXTENSION)) -c $(*:%=$(%%_CHIMERAS_OUTPUT_DIRECTORY)/%$(%%_CHIMERAS_EXTENSION))
