## DESCRIPTION
# STAR is a Mapping softwares that is able to align spliced reads to a reference genome.

## SYNOPSIS
# In order to run STAR, one only need to specify a STAR index, sequence files 
# (in FASTA/FASTQ) and a prefix for the output files.

## INPUT VARS:
%%_INDEX 							= undef# Filename of the index to be used
%%_READS 							= undef# List of reads files (FASTA or FASTQ) to be passed to STAR

## OUTPUT VARS
%%_OUTPUT_PREFIX			= STAR# Prefix for name of the output files (see below)
%%_OUTPUT_FILE				= $(%%_OUTPUT_PREFIX)/mapping.bam# SAM/BAM file generated by STAR
%%_LOG_FILE       		= $(%%_OUTPUT_PREFIX).log# Log file from STDERR
%%_JUNCTION_FILE			= $(%%_OUTPUT_PREFIX)/SJ.out.tab

## OPTIONS
%%_BINARY 						= STAR# Binary to use for running 
%%_NB_THREADS					= 1# Number of threads allocated to the cractools binary
%%_OPTIONS 						= # Options that can be specified to STAR (see STAR doc for more information) 
%%_SORT_BAM						= true# If true, output bam will be piped to samtools for sorting

## COMPUTED VARS
%%_VERSION 						= $(shell $(%%_BINARY) --version) # STAR version

%%_OPTIONS += --genomeDir $(%%_INDEX) --runThreadN $(%%_NB_THREADS) --readFilesIn $(%%_READS)# STAR Options
%%_PRODUCED_FILES = $(%%_OUTPUT_FILE) $(%%_NOVEL_SPLICE_FILE) $(%%_LOG_FILE)

%%_OPTIONS += --outFileNamePrefix $(%%_OUTPUT_PREFIX)/

# Set options for compressed files
ifeq ($(firstword $(suffix $(%%_READS))), .gz)
%%_OPTIONS += --readFilesCommand zcat
endif

# Set chimera output file if "--chimSegmentMine" option is provided
ifneq ($(findstring --chimSegmentMin,$(%%_OPTIONS)),)
%%_CHIMERA_FILE				= $(%%_OUTPUT_PREFIX)/Chimeric.out.junction
endif

# if SORTED_BAME is requested add proper options
ifeq ($(%%_SORT_BAM),true)
%%_OPTIONS += --outStd BAM_SortedByCoordinate --outSAMtype BAM SortedByCoordinate
else
%%_OPTIONS += --outStd BAM_Unsorted --outSAMtype BAM Unsorted
endif

.PHONY: %%

%%: $(%%_OUTPUT_FILE)

# Set dependency for the junction file
$(%%_JUNCTION_FILE): $(%%_OUTPUT_FILE)
$(%%_CHIMERA_FILE): $(%%_OUTPUT_FILE)

%%_clean:
	-rm $(%%_PRODUCED_FILES)
	-rmdir -p --ignore-fail-on-non-empty $(dir $(%%_OUTPUT_FILE))

.SERIAL: $(%%_OUTPUT_FILE)
$(%%_OUTPUT_FILE): $(%%_READS)
	mkdir -p $(dir $@)
	$(%%_BINARY) $(%%_OPTIONS) > $@ 2> $(%%_LOG_FILE) $(%%_PIPE_COMMANDS)
